### ISSUE TITLE
Consult scavenger hunt list while preparing project for presentation (list in comments)

### ISSUE THREAD

**Issue by makijurowski** [WatPi/WatPi#31]
Link here: https://gist.github.com/pinkshrub/2f60ce25144c2b8349877d6cbfb903bb

Should we try for a green belt?

**Comment by makijurowski** [comment]
Full list including updates:

## Creativity + Cool-Factor
- [ ]  1 - Novel Idea
- [ ]  1 - 5 New Technology
- [ ]  1 - Bring Cookies for Instructor
- [ ]  1 - Activity Day Attendance
- [ ]  1 - Moments of Hacking
- [ ]  1 - Wearing a green belt during presentations

## Complexity
- [ ]  2 - Use of an API
- [ ]  1 - 5 Use of JQuery/SPA
- [ ]  5 - Use of 3rd party login/auth system
- [ ]  .5 - 1 - Feature
- [ ]  1-3 - CRUD resource

## Completeness
- [ ]  1 - 5 "Relevant" tests
- [ ]  1 - Github History presented
- [ ]  2 - Excellent Python Style
- [ ]  5 - Presentation
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- Delivery/preparedness 
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- Content 
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- Rose/Bud/Thorn 
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- Reflections 
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- Learnings
- [ ] 1 - Domain Name
- [ ] 2 - Deployed in the real world!
- [ ] 1-2 - Accessible design
- [ ] 2 - Responsive design

**Comment by ayuspark** [comment]
:(
