### ISSUE TITLE
Tests for rover movement and camera (see new comment)

### ISSUE THREAD

**Issue by makijurowski** [WatPi/WatPi#5]

**Comment by makijurowski** [comment]
Especially while we're pulling things together right now, it'd be good to have a few tests that we could run to make sure any code we add or refactor doesn't break WatPi's functionality. I'm not sure how to do it yet, but my thought is some tests that:

- Make sure rover output is being sent
- Make sure camera output is being sent
- Make sure login/dashboard site render
- Make sure files are being saved

**Comment by ayuspark** [comment]
DONE.
