### ISSUE TITLE
Wireframes for MVP version of dashboard.

### ISSUE THREAD

**Issue by makijurowski** [WatPi/WatPi#7]
Initial proposal:
![wireframes](https://user-images.githubusercontent.com/18458620/31320600-11b0d0e2-ac2c-11e7-9b58-72a37a513d1d.png)

Boring but hopefully functional. Feedback welcome.

.zip contains .bmml file for editing in mybalsamiq.
[Initial Mockup.bmml.zip](https://github.com/WatPi/WatPi/files/1367182/Initial.Mockup.bmml.zip)

**Comment by ayuspark** [comment]
#### Suggestion:
Maybe we can use a "game control" for the control panel. See codez link below:
https://codepen.io/Illusion/pen/dopjOx
