### ISSUE TITLE
Find a place to share and store resources

### ISSUE THREAD

**Issue by ayuspark** [WatPi/WatPi#8]
We are currently using Slack to share resources. I wonder if we can use a github feature/app to store and *organise* all these resources, for knowledge management purposes.

**Comment by makijurowski** [comment]
I've been looking at options and surprised to find so few that offer Github integration or a convenient way to share across devices. 

Until we find a better solution, I started a wiki page with a list of links that were either submitted via Slack/MatterMost or relevant from my project bookmarks, alphabetized by heading to help keep things organized: <https://github.com/WatPi/WatPi/wiki>

**Comment by makijurowski** [comment]
Closing out this issue to tidy things up, but still open to suggestions as an alternative to a wiki list.
